### ISSUE TITLE
Replace community rules with non-default rules

### ISSUE THREAD

**Issue by bhirsz** [bhirsz/robotframework-cop-academy#33]
It's tough subject. Recently we have introduced 'Community' rules in order to encourage users to add their rules to Robocop. It's probably not fully related but recently we had bit more user contributions to rules. But there is one issue: some rules align well with the idea of 'community' rules (non-default, optional rules made by community) and some not (for example they are good enough to be always enabled). 

This leads me to thinking that we should drop this innitiave altogether. We invested some time in it, but not all is lost - for example it's not possible to have non-default, disabled rules in the repository. Users should be encouraged to put their rules directly in the Robocop, and we can decide on the default/non-default status in their PRs.

@mnojek WDYT?

**Comment by mnojek** [comment]
I agree :D
